# Run docker-compose up
# Live long and prosper

version: '2'

services:

  nginx:
    container_name: nginx_container
    restart: always
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - skf-angular
      - skf-api

    rabbit:
      image: rabbitmq:latest
      environment:
          - RABBITMQ_DEFAULT_USER=admin
          - RABBITMQ_DEFAULT_PASS=admin
      ports:
          - "5672:5672"
          - "15672:15672"

  skf-angular:
    container_name: skf-angular_container
    restart: always
    image: "blabla1337/skf-angular:1.3"
    environment:
      - FRONTEND_URI=https://localhost

  skf-api:
    container_name: skf-api_container
    restart: always
    image: "blabla1337/skf-api:1.3"
    environment:
      - SKF_FLASK_DEBUG=False
      - SKF_API_URL=https://localhost/api
      - SKF_TESTING=False
      #- SKF_DB_URL=mysql+pymysql://root:password@localhost/skf?charset=utf8mb4
      #- SKF_DB_URL=
      #- SKF_DOJO_API_KEY=
      #- JWT_SECRET=


