apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config-skf-flask
data:
  ORIGIN: skf-flask-back
  JWT_SECRET: test
  key.test: test_config_map_value
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skf-flask-back
data:
  JWT_SECRET: dasdasdsadasd
  SKF_API_URL: https://localhost/api
  SKF_FLASK_DEBUG: "False"
  SKF_DB_URL: sqlite:///db/db.sqlite
  SKF_DOJO_API_KEY: optional
  SKF_DOJO_API_KEY: optional
  SKF_TESTING: "False"
  RABBIT_MQ_CONN_STRING: rabbitmq
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skf-flask-front
data:
  FRONTEND_URI: https://localhost
---  
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
data:
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: admin-skf-secret