apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config-skf-flask
data:
  ORIGIN: skf-flask-back
  JWT_SECRET: test
  key.test: test_config_map_value
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skf-flask-back
data:
  JWT_SECRET: changeme1
  key.test: test_config_map_value
  SKF_API_URL: skf-flask-back.default.svc.cluster.local:8888
  SKF_FLASK_DEBUG: "False"
  SKF_DB_URL: sqlite:///db/db.sqlite
  SKF_DOJO_API_KEY: optional
  SKF_DOJO_API_KEY: optional
  SKF_TESTING: "False"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skf-flask-front
data:
  FRONTEND_URI: http://127.0.0.1:8081
  BACKEND_URI: http://skf-flask-back.default.svc.cluster.local:8888
  SERVER_CERT_KEY: ""
  SERVER_CERT_PATH: ""
  TLS: "false"
  key.test: test_config_map_value
